#!/bin/bash

# MT5 Server Deployment Script
# This script helps deploy the MT5 server on a VPS

set -e

echo "🚀 Starting MT5 Server Deployment"

# Check if running as root or with sudo
if [[ $EUID -eq 0 ]]; then
   echo "❌ This script should not be run as root for security reasons"
   exit 1
fi

# Function to display colored output
print_status() {
    echo -e "\033[1;34m$1\033[0m"
}

print_success() {
    echo -e "\033[1;32m✅ $1\033[0m"
}

print_error() {
    echo -e "\033[1;31m❌ $1\033[0m"
}

print_warning() {
    echo -e "\033[1;33m⚠️  $1\033[0m"
}

# Check system requirements
print_status "Checking system requirements..."

# Check OS
if [[ "$OSTYPE" != "linux-gnu"* ]]; then
    print_error "This script is designed for Linux systems only"
    exit 1
fi

# Check architecture
ARCH=$(uname -m)
if [[ "$ARCH" != "x86_64" ]]; then
    print_error "This script requires x86_64 architecture"
    exit 1
fi

print_success "System requirements met"

# Install system dependencies
print_status "Installing system dependencies..."

sudo apt update
sudo apt install -y \
    python3 \
    python3-pip \
    python3-venv \
    curl \
    wget \
    gnupg2 \
    software-properties-common \
    ca-certificates \
    build-essential \
    libssl-dev \
    libffi-dev \
    python3-dev \
    git

print_success "System dependencies installed"

# Create application directory
APP_DIR="$HOME/mt5-server"
print_status "Setting up application directory: $APP_DIR"

if [[ -d "$APP_DIR" ]]; then
    print_warning "Directory $APP_DIR already exists. Backing up..."
    mv "$APP_DIR" "${APP_DIR}.backup.$(date +%Y%m%d_%H%M%S)"
fi

mkdir -p "$APP_DIR"
cd "$APP_DIR"

print_success "Application directory created"

# Copy application files (assuming they're in the current directory)
print_status "Copying application files..."

# Copy all necessary files
cp -r . "$APP_DIR/"

print_success "Application files copied"

# Create Python virtual environment
print_status "Creating Python virtual environment..."

python3 -m venv venv
source venv/bin/activate

print_success "Virtual environment created"

# Install Python dependencies
print_status "Installing Python dependencies..."

pip install --upgrade pip
pip install -r requirements.txt

print_success "Python dependencies installed"

# Generate encryption key
print_status "Generating encryption key..."

ENCRYPTION_KEY=$(python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())")

print_success "Encryption key generated"

# Create .env file
print_status "Creating environment configuration..."

if [[ ! -f ".env" ]]; then
    cat > .env << EOF
# MT5 VPS Server Environment Configuration
# Generated by deployment script on $(date)

# ==========================================
# SUPABASE AUTHENTICATION
# ==========================================
SUPABASE_URL=https://your-project.supabase.co
SUPABASE_ANON_KEY=your-supabase-anon-key
SUPABASE_JWT_SECRET=JAy9Bi8qCw9xgtSJV9WsW9VIbcqTcWsQqUDXUSxj0Ifj39ccmXdCuIAN3jatAlkbGs/pndCWT7iInDT0DDnOiQ==

# ==========================================
# MT5 SERVER CONFIGURATION
# ==========================================
MT5_PATH=/config/.wine/drive_c/Program Files/MetaTrader 5
MT5_SERVER_PORT=8001
MT5_ENCRYPTION_KEY=${ENCRYPTION_KEY}

# ==========================================
# API SECURITY
# ==========================================
API_KEYS=your-api-key-1,your-api-key-2,your-api-key-3
ALLOWED_IPS=127.0.0.1,::1
JWT_SECRET=your-jwt-secret-for-internal-use
JWT_ALGORITHM=HS256
JWT_ACCESS_TOKEN_EXPIRE_MINUTES=30

# ==========================================
# RATE LIMITING
# ==========================================
REQUESTS_PER_MINUTE=60
BURST_LIMIT=10
WEBSOCKET_CONNECTIONS_MAX=100

# ==========================================
# WEBSOCKET CONFIGURATION
# ==========================================
WS_HOST=0.0.0.0
WS_PORT=8765
WS_PING_INTERVAL=30
WS_PING_TIMEOUT=10

# ==========================================
# REST API CONFIGURATION
# ==========================================
API_HOST=0.0.0.0
API_PORT=8000
API_WORKERS=4
API_DEBUG=false

# ==========================================
# LOGGING CONFIGURATION
# ==========================================
LOG_LEVEL=INFO
LOG_FORMAT=json
LOG_FILE=/var/log/mt5-server.log
LOG_MAX_SIZE=100MB
LOG_BACKUP_COUNT=5

# ==========================================
# MONITORING & METRICS
# ==========================================
ENABLE_METRICS=true
METRICS_PORT=9090
HEALTH_CHECK_INTERVAL=30

# ==========================================
# MARKET DATA CONFIGURATION
# ==========================================
MARKET_DATA_CACHE_SIZE=1000
MARKET_DATA_UPDATE_INTERVAL=200
HISTORICAL_DATA_CACHE_TTL=3600

# ==========================================
# RISK MANAGEMENT
# ==========================================
MAX_POSITION_SIZE_PCT=0.1
MAX_DAILY_LOSS_PCT=0.05
MAX_CONCURRENT_TRADES=10
DEFAULT_STOP_LOSS_PIPS=50
DEFAULT_TAKE_PROFIT_PIPS=100

# ==========================================
# DEVELOPMENT/DEBUG SETTINGS
# ==========================================
DEBUG_MODE=false
ENABLE_SWAGGER_DOCS=false
ENABLE_CORS=true
CORS_ORIGINS=https://your-frontend-domain.com,https://localhost:3000

# ==========================================
# MT5 TERMINAL SETTINGS
# ==========================================
MT5_AUTO_LOGIN=true
MT5_CONNECTION_TIMEOUT=30
MT5_RECONNECT_ATTEMPTS=5
MT5_RECONNECT_DELAY=10

# ==========================================
# PERFORMANCE TUNING
# ==========================================
MAX_WORKERS=4
THREAD_POOL_SIZE=10
ASYNCIO_MAX_WORKERS=20
MEMORY_CACHE_SIZE_MB=512

# ==========================================
# ALERTS & MONITORING
# ==========================================
ALERT_WEBHOOK_URL=
ALERT_ON_DISCONNECTION=true
ALERT_ON_HIGH_LATENCY=true
LATENCY_THRESHOLD_MS=1000

# ==========================================
# FEATURE FLAGS
# ==========================================
ENABLE_REAL_TIME_TRADING=true
ENABLE_PAPER_TRADING=true
ENABLE_STRATEGY_BACKTESTING=true
ENABLE_MARKET_DATA_STREAMING=true
ENABLE_ORDER_MANAGEMENT=true
ENABLE_POSITION_TRACKING=true
ENABLE_RISK_MANAGEMENT=true
ENABLE_PERFORMANCE_ANALYTICS=true
EOF

    print_success "Environment file created: .env"
    print_warning "⚠️  IMPORTANT: Please edit the .env file and configure:"
    echo "   - SUPABASE_URL and SUPABASE_ANON_KEY"
    echo "   - API_KEYS for authentication"
    echo "   - CORS_ORIGINS for your frontend domain"
    echo "   - Any other service-specific settings"
else
    print_warning "Environment file already exists, skipping creation"
fi

# Create systemd service
print_status "Creating systemd service..."

SERVICE_NAME="mt5-server"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"

sudo tee "$SERVICE_FILE" > /dev/null << EOF
[Unit]
Description=MT5 Trading Server
After=network.target
Wants=network.target

[Service]
Type=simple
User=$USER
WorkingDirectory=$APP_DIR
Environment=PATH=$APP_DIR/venv/bin
ExecStart=$APP_DIR/venv/bin/python $APP_DIR/mt5_server.py
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal
SyslogIdentifier=mt5-server

# Security settings
NoNewPrivileges=yes
PrivateTmp=yes
ProtectSystem=strict
ReadWritePaths=$APP_DIR
ProtectHome=yes

# Resource limits
MemoryLimit=2G
CPUQuota=400%

[Install]
WantedBy=multi-user.target
EOF

print_success "Systemd service created"

# Create log directory
print_status "Setting up logging..."

sudo mkdir -p /var/log
sudo touch /var/log/mt5-server.log
sudo chown $USER:$USER /var/log/mt5-server.log

print_success "Logging configured"

# Set up log rotation
print_status "Setting up log rotation..."

sudo tee /etc/logrotate.d/mt5-server > /dev/null << EOF
/var/log/mt5-server.log {
    daily
    missingok
    rotate 7
    compress
    delaycompress
    notifempty
    create 644 $USER $USER
    postrotate
        systemctl reload mt5-server
    endscript
}
EOF

print_success "Log rotation configured"

# Create data directories
print_status "Creating data directories..."

mkdir -p data
mkdir -p logs
mkdir -p cache

print_success "Data directories created"

# Test the installation
print_status "Testing installation..."

# Test Python imports
if python3 -c "import fastapi, uvicorn, websockets, jwt, cryptography"; then
    print_success "Python dependencies test passed"
else
    print_error "Python dependencies test failed"
    exit 1
fi

print_success "Installation test completed"

# Final instructions
echo ""
echo "🎉 MT5 Server deployment completed successfully!"
echo ""
echo "📋 Next steps:"
echo "1. Edit the .env file with your configuration:"
echo "   nano $APP_DIR/.env"
echo ""
echo "2. Start the service:"
echo "   sudo systemctl daemon-reload"
echo "   sudo systemctl enable mt5-server"
echo "   sudo systemctl start mt5-server"
echo ""
echo "3. Check service status:"
echo "   sudo systemctl status mt5-server"
echo ""
echo "4. View logs:"
echo "   sudo journalctl -u mt5-server -f"
echo ""
echo "5. Test the API:"
echo "   curl http://localhost:8000/"
echo ""
echo "🔗 Service URLs:"
echo "   - REST API: http://your-server-ip:8000"
echo "   - WebSocket: ws://your-server-ip:8765"
echo "   - Health Check: http://your-server-ip:8000/health"
echo ""
echo "📚 Useful commands:"
echo "   - Restart: sudo systemctl restart mt5-server"
echo "   - Stop: sudo systemctl stop mt5-server"
echo "   - Logs: sudo journalctl -u mt5-server -f"
echo ""
print_warning "⚠️  Remember to:"
echo "   - Configure your firewall to allow ports 8000 and 8765"
echo "   - Set up SSL/TLS certificates for production"
echo "   - Configure monitoring and alerting"
echo "   - Set up regular backups"